; PlatformIO Project Configuration File for Estero-Volt
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32 @ 6.5.0
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_RUNNING_CORE=1
    -D ARDUINO_EVENT_RUNNING_CORE=1

lib_deps = 
    sandeepmistry/LoRa @ ^0.8.0

board_build.f_cpu = 80000000L   ; Downclock CPU to 80 MHz to slash active run current from 60mA to 25mA
board_build.flash_mode = dio
board_build.f_flash = 40000000L
